//! Shared loader for the Temporal+Spatial Parquet Ingestion Rust SDK example.
//!
//! Reads `../data/sample.parquet` (generated by the Python
//! `00-make-sample.py`) and lands rows into ArcFlow's graph shape:
//!
//! ```text
//! (:Entity {entity_id})-[:OBSERVED_AT {x, y, frame, play, _confidence, _observation_class, _source}]->(:Frame {frame})
//! ```

use anyhow::{Context, Result};
use arcflow_sdk::ConcurrentStore;
use arrow::record_batch::RecordBatch;
use duckdb::Connection;
use parquet::arrow::arrow_reader::ParquetRecordBatchReaderBuilder;
use std::fs::File;
use std::path::Path;

/// Load the Parquet into BOTH ArcFlow and DuckDB so step 05 can run
/// cross-engine validation on the same input.
pub fn load_both(parquet_path: &Path) -> Result<(ConcurrentStore, Connection)> {
    let graph = arcflow_sdk::open_concurrent();
    let sql = Connection::open_in_memory()?;

    // DuckDB sees the Parquet directly via its arrow integration —
    // simplest cross-engine validation surface.
    sql.execute(
        &format!(
            "CREATE TABLE tracking AS SELECT * FROM read_parquet('{}')",
            parquet_path.display(),
        ),
        [],
    )?;

    // ArcFlow loads the same rows into the graph shape.
    let file = File::open(parquet_path)
        .with_context(|| format!("opening {}", parquet_path.display()))?;
    let builder = ParquetRecordBatchReaderBuilder::try_new(file)?;
    let reader = builder.build()?;

    let mut entities_seen = std::collections::HashSet::new();
    let mut frames_seen = std::collections::HashSet::new();

    for batch in reader {
        let batch: RecordBatch = batch?;
        let n = batch.num_rows();

        let entity_col = column_string(&batch, "entity_id")?;
        let frame_col  = column_i64(&batch, "frame")?;
        let x_col      = column_f64(&batch, "x")?;
        let y_col      = column_f64(&batch, "y")?;

        for i in 0..n {
            let entity = &entity_col[i];
            let frame = frame_col[i];
            let x = x_col[i];
            let y = y_col[i];

            if entities_seen.insert(entity.clone()) {
                graph.execute(&format!(
                    "CREATE (:Entity {{entity_id: '{entity}', \
                        _observation_class: 'observed', _confidence: 1.0, \
                        _source: 'roster_v1'}})"
                ))?;
            }
            if frames_seen.insert(frame) {
                graph.execute(&format!(
                    "CREATE (:Frame {{frame: {frame}, \
                        _observation_class: 'observed', _confidence: 1.0, \
                        _source: 'master_clock_v1'}})"
                ))?;
            }

            graph.execute(&format!(
                "MATCH (e:Entity {{entity_id: '{entity}'}}), \
                       (f:Frame {{frame: {frame}}}) \
                 CREATE (e)-[:OBSERVED_AT {{ \
                    x: {x:.3}, y: {y:.3}, frame: {frame}, \
                    _confidence: 0.95, _observation_class: 'observed', \
                    _source: 'tracker_v1' \
                 }}]->(f)"
            ))?;
        }
    }

    Ok((graph, sql))
}

fn column_string(batch: &RecordBatch, name: &str) -> Result<Vec<String>> {
    let col = batch.column_by_name(name)
        .with_context(|| format!("column {name} missing"))?;
    let arr = col.as_any()
        .downcast_ref::<arrow::array::StringArray>()
        .with_context(|| format!("column {name} not a string"))?;
    Ok((0..arr.len()).map(|i| arr.value(i).to_string()).collect())
}

fn column_i64(batch: &RecordBatch, name: &str) -> Result<Vec<i64>> {
    let col = batch.column_by_name(name)
        .with_context(|| format!("column {name} missing"))?;
    let arr = col.as_any()
        .downcast_ref::<arrow::array::Int64Array>()
        .with_context(|| format!("column {name} not i64"))?;
    Ok((0..arr.len()).map(|i| arr.value(i)).collect())
}

fn column_f64(batch: &RecordBatch, name: &str) -> Result<Vec<f64>> {
    let col = batch.column_by_name(name)
        .with_context(|| format!("column {name} missing"))?;
    let arr = col.as_any()
        .downcast_ref::<arrow::array::Float64Array>()
        .with_context(|| format!("column {name} not f64"))?;
    Ok((0..arr.len()).map(|i| arr.value(i)).collect())
}
