// ArcFlow Schema Codegen (I-INIT-0050)
//
// extractSchema(db)      — reads CALL db.schema and returns a GraphSchema.
// generateTypeScript(s)  — turns a GraphSchema into TypeScript interface source.
//
// Primary path: import { extractSchema, generateTypeScript } from 'arcflow/codegen'
// CLI:          arcflow-codegen --lang ts --output types.ts <data-dir>

import type { ArcflowDB } from './types'

// ---------------------------------------------------------------------------
// Schema model
// ---------------------------------------------------------------------------

/** A node type inferred from the graph schema. */
export interface NodeType {
	/** Node label. */
	label: string
	/** Property names observed on this label (no guaranteed order). */
	properties: string[]
	/** Number of nodes with this label at extraction time. */
	count: number
}

/** A relationship pattern observed in the graph. */
export interface RelType {
	/** Full pattern string, e.g. `(:Person)-[:KNOWS]->(:Person)`. */
	pattern: string
}

/** Extracted graph schema from a live ArcFlow database. */
export interface GraphSchema {
	/** All node types (one per label). */
	nodeTypes: NodeType[]
	/** All relationship patterns. */
	relTypes: RelType[]
	/** ISO-8601 timestamp when this schema was extracted. */
	extractedAt: string
}

// ---------------------------------------------------------------------------
// Extraction
// ---------------------------------------------------------------------------

/**
 * Extract the graph schema from an open ArcFlow database.
 *
 * Calls `CALL db.schema` which returns a snapshot of all labels, their
 * property keys (from sampled nodes), and relationship patterns.
 *
 * @example
 * const db = open('./my-graph')
 * const schema = extractSchema(db)
 * console.log(schema.nodeTypes.map(n => n.label))
 */
export function extractSchema(db: ArcflowDB): GraphSchema {
	const result = db.query('CALL db.schema')
	const nodeTypes: NodeType[] = []
	const relTypes: RelType[] = []

	for (const row of result.rows) {
		const label = String(row.get('label') ?? '')
		const propertiesRaw = String(row.get('properties') ?? '')
		const countRaw = row.get('count')

		if (!label) {
			// Relationship pattern row (label is empty string)
			const pattern = propertiesRaw.trim()
			if (pattern) relTypes.push({ pattern })
			continue
		}

		const properties = propertiesRaw
			.split(',')
			.map(p => p.trim())
			.filter(p => p.length > 0)

		const count = countRaw !== null ? Number(countRaw) : 0

		nodeTypes.push({ label, properties, count })
	}

	return {
		nodeTypes,
		relTypes,
		extractedAt: new Date().toISOString(),
	}
}

// ---------------------------------------------------------------------------
// TypeScript codegen
// ---------------------------------------------------------------------------

/** Options for TypeScript code generation. */
export interface TypeScriptCodegenOptions {
	/** Include a comment header with generation timestamp. Default: true. */
	header?: boolean
	/** Property value type for each property. Default: `string | number | boolean | null`. */
	propertyType?: string
	/** Include node count as a JSDoc comment. Default: true. */
	nodeCountComment?: boolean
}

/**
 * Generate TypeScript interface declarations from a `GraphSchema`.
 *
 * Each node label becomes a `${Label}Node` interface with optional properties
 * typed as `string | number | boolean | null` (ArcFlow's scalar property types).
 * An index signature `[key: string]: unknown` allows extra properties without
 * breaking existing code.
 *
 * Relationship patterns are emitted as a `RelationshipPattern` string union.
 * An `AnyNode` union covers all node types.
 *
 * @example
 * const code = generateTypeScript(schema)
 * // → interface PersonNode { name?: string | number | boolean | null; ... }
 */
export function generateTypeScript(
	schema: GraphSchema,
	options: TypeScriptCodegenOptions = {},
): string {
	const {
		header = true,
		propertyType = 'string | number | boolean | null',
		nodeCountComment = true,
	} = options

	const lines: string[] = []

	if (header) {
		lines.push('// Auto-generated by ArcFlow codegen. Do not edit manually.')
		lines.push(`// Extracted: ${schema.extractedAt}`)
		lines.push('')
	}

	// Node interfaces
	for (const node of schema.nodeTypes) {
		const interfaceName = `${pascalCase(node.label)}Node`

		if (nodeCountComment) {
			lines.push(`/** ${node.label} node — ${node.count} node${node.count === 1 ? '' : 's'} at extraction time. */`)
		}
		lines.push(`export interface ${interfaceName} {`)

		for (const prop of node.properties) {
			lines.push(`  ${safeIdent(prop)}?: ${propertyType}`)
		}

		lines.push('  [key: string]: unknown')
		lines.push('}')
		lines.push('')
	}

	// AnyNode union
	if (schema.nodeTypes.length > 0) {
		const union = schema.nodeTypes.map(n => `${pascalCase(n.label)}Node`).join(' | ')
		lines.push('/** Union of all node types in the graph. */')
		lines.push(`export type AnyNode = ${union}`)
		lines.push('')
	}

	// RelationshipPattern union
	if (schema.relTypes.length > 0) {
		lines.push('/** Relationship patterns observed in the graph. */')
		lines.push('export type RelationshipPattern =')
		for (let i = 0; i < schema.relTypes.length; i++) {
			const sep = i < schema.relTypes.length - 1 ? '' : ''
			lines.push(`  | ${JSON.stringify(schema.relTypes[i].pattern)}${sep}`)
		}
		lines.push('')
	}

	return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Convert a label/property name to PascalCase, stripping non-identifier chars. */
function pascalCase(s: string): string {
	return s
		.replace(/[^a-zA-Z0-9_$]+(.)?/g, (_, c: string | undefined) =>
			c ? c.toUpperCase() : '',
		)
		.replace(/^(.)/, (_, c: string) => c.toUpperCase())
}

/** Ensure a property name is a safe JS identifier; quote it if needed. */
function safeIdent(prop: string): string {
	if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(prop)) return prop
	return JSON.stringify(prop)
}
